# Site settings
title: Amaraa blog
email: 
description: "everything about the universe"
baseurl: ""
url: "http://asaamaraa.github.io"
twitter_username: asaamaraa
github_username:  asaamraa

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
